// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkeaawukzmbtowvnenpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrZWFhd3Vrem1idG93dm5lbnBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDAzODUsImV4cCI6MjA2NjI3NjM4NX0.5azT7atUAw3nLd-_rYnJQFSpPdbpSN3eIgVwaYjix28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);